export { default as HomePage } from './Home';
export { default as FranchisePage } from './Franchise';
export { default as ShopPage } from './Shop';
export { default as CoinsPage } from './Coins';
export { default as BarsPage } from './Bars';
export { default as ProductPage } from './Product';
export { default as CartPage } from './Cart';
export { default as LoginPage } from './Login';
export { default as AccountPage } from './Account';
